package none.CoderCanvas;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Noahb
 */
public class CodeEditorInternalFrame extends javax.swing.JInternalFrame {
    private JPanel panel;
    private RSyntaxTextArea editorTextArea;
    private RTextScrollPane scrollerPanel;

    /**
     * Creates new form internalEditor
     */
    public CodeEditorInternalFrame() {
        panel = new JPanel(new BorderLayout());
        editorTextArea = new RSyntaxTextArea(20, 60);
        editorTextArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
        editorTextArea.setCodeFoldingEnabled(true);
        scrollerPanel = new RTextScrollPane(editorTextArea);
        panel.add(scrollerPanel);
        
        initComponents();
        setContentPane(panel);
    }
    
    public String getContents(){
        return editorTextArea.getText();
    }
    public void setContents(String text){
        editorTextArea.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
