/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package none.CoderCanvas;

import com.google.gson.Gson;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Noahb
 */
public class PlannerWin extends javax.swing.JFrame {
    private User user;
    private DefaultComboBoxModel<Course> dlmCourses;
    private DefaultListModel<Assignment> dlmAssignments;
    private DefaultListModel<Assignment> dlmTodo;
    private Course currentCourse;
    private String currentFilter;
    private Assignment currentAssignment;
    /**
     * Creates new form planWindow
     */
    public PlannerWin(User user) {
        this.user = user;
        dlmCourses = new DefaultComboBoxModel();
        dlmCourses.addAll(user.getCourses());
        dlmAssignments = new DefaultListModel();
        dlmTodo = new DefaultListModel();
        dlmTodo.addAll(user.getTodo());
        currentFilter = "None";
        initComponents();
        lstAssignments.setCellRenderer(new AssignmentCellRender());
        lstTodo.setCellRenderer(new AssignmentCellRender());
    }
    
    public void updateAssignments(){
        dlmAssignments.clear();
        if(currentFilter == "None"){
            for(Assignment assignment: currentCourse.getAssignments()){
                dlmAssignments.addElement(assignment);
            }
        }
        else if(currentFilter == "Not Submitted"){
            for(Assignment assignment: currentCourse.getAssignments()){
                if(!assignment.isDone()){
                    dlmAssignments.addElement(assignment);
                }
            }
            
        }
        else if(currentFilter == "Not Past Due"){
            Date now = new Date();
            for(Assignment assignment: currentCourse.getAssignments()){
                Date due = assignment.getDueAt();
                if(due != null){
                    if(now.before(due)){
                       dlmAssignments.addElement(assignment);
                    }
                }
                else{
                    dlmAssignments.addElement(assignment);
                }
            }
        }
    }
    public void updateCurrentAssignment(){
        if(currentAssignment != null){
            sldProgress.setValue(currentAssignment.getProgress());
            tpNotes.setText(currentAssignment.getNotes());
        }
    }
    public void saveCurrentAssignment(){
        if(currentAssignment != null){  
            int amt = sldProgress.getValue();
            String notes = tpNotes.getText();
            currentAssignment.setProgress(amt);
            currentAssignment.setNotes(notes);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbCourses = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAssignments = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTodo = new javax.swing.JList<>();
        sldProgress = new javax.swing.JSlider();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpNotes = new javax.swing.JTextPane();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        cbFilter = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Assignment Planner");

        cbCourses.setModel(dlmCourses);
        cbCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCoursesActionPerformed(evt);
            }
        });

        lstAssignments.setModel(dlmAssignments);
        lstAssignments.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAssignmentsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstAssignments);

        lstTodo.setModel(dlmTodo);
        lstTodo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTodoValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstTodo);

        sldProgress.setValue(0);
        sldProgress.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldProgressStateChanged(evt);
            }
        });
        sldProgress.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                sldProgressCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        tpNotes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tpNotesPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tpNotes);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Complete");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        cbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Not Submitted", "Not Past Due", " " }));
        cbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilterActionPerformed(evt);
            }
        });

        jLabel1.setText("Filter By:");

        jButton2.setText("Save Todo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("TODO LIST:");

        jLabel3.setText("Assignments:");

        jLabel4.setText("Courses:");

        jLabel5.setText("My Notes:");

        jLabel6.setText("My Progress:");

        jLabel7.setText("0");

        jLabel8.setText("100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 361, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRemove)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sldProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(333, 333, 333)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sldProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCoursesActionPerformed
        currentCourse = (Course)cbCourses.getSelectedItem();
        updateAssignments();
    }//GEN-LAST:event_cbCoursesActionPerformed

    private void cbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilterActionPerformed
        currentFilter = (String)cbFilter.getSelectedItem();
        updateAssignments();
    }//GEN-LAST:event_cbFilterActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Assignment val = lstAssignments.getSelectedValue();
        if(val != null){
            val.markTodo(new Gson());
            user.addTodo(val);
            user.addTodoId(val.getId());
            dlmTodo.addElement(val);
        }  
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        sldProgress.setValue(0);
        tpNotes.setText("");
        int idx = lstTodo.getSelectedIndex();
        if(idx > -1){
            user.removeTodoId(idx);
            user.removeTodo(idx);
            dlmTodo.remove(idx);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void lstTodoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTodoValueChanged
       saveCurrentAssignment();
       currentAssignment = lstTodo.getSelectedValue();
       updateCurrentAssignment();
    }//GEN-LAST:event_lstTodoValueChanged

    private void sldProgressCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_sldProgressCaretPositionChanged
        
    }//GEN-LAST:event_sldProgressCaretPositionChanged

    private void sldProgressStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldProgressStateChanged

    }//GEN-LAST:event_sldProgressStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
           saveCurrentAssignment();
           user.saveTodo();
           for(int i = 0; i < dlmTodo.size(); i++){
               dlmTodo.get(i).saveTodo();
           }
        }
        catch(Exception e){}      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tpNotesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tpNotesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tpNotesPropertyChange

    private void lstAssignmentsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAssignmentsValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstAssignmentsValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<Course> cbCourses;
    private javax.swing.JComboBox<String> cbFilter;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<Assignment> lstAssignments;
    private javax.swing.JList<Assignment> lstTodo;
    private javax.swing.JSlider sldProgress;
    private javax.swing.JTextPane tpNotes;
    // End of variables declaration//GEN-END:variables
}
